var decLiteral = 9527;
var hexLiteral = 0x2537;
var binaryLiteral = 9527;
var octLiteral = 9527;
var notANumber = NaN;
var infinityNumber = Infinity;
console.log(decLiteral, typeof decLiteral);
console.log(hexLiteral, typeof hexLiteral);
console.log(binaryLiteral, typeof binaryLiteral);
console.log(octLiteral, typeof octLiteral);
console.log(infinityNumber, typeof infinityNumber);
console.log(notANumber, typeof notANumber);
console.log((decLiteral + hexLiteral) / 2);
